import type { MapListing } from "./map-types";

export const mapSampleListings: MapListing[] = [
  {
    id: 1,
    title: "청년안심주택 공고",
    address: "서울특별시 마포구 공덕동",
    region: "서울",
    depositLabel: "보증금 1,000만",
    monthlyRentLabel: "월세 45만",
    latitude: 37.5446,
    longitude: 126.9519,
    tags: ["청년", "역세권", "공공지원"],
    category: "oneRoom",
  },
  {
    id: 2,
    title: "LH 청년매입임대",
    address: "서울특별시 강서구 화곡동",
    region: "서울",
    depositLabel: "보증금 200만",
    monthlyRentLabel: "월세 30만",
    latitude: 37.541,
    longitude: 126.8405,
    tags: ["LH", "청년임대"],
    category: "villa",
  },
  {
    id: 3,
    title: "행복주택 모집공고",
    address: "경기도 고양시 덕양구",
    region: "경기",
    depositLabel: "보증금 800만",
    monthlyRentLabel: "월세 38만",
    latitude: 37.6584,
    longitude: 126.832,
    tags: ["행복주택", "신혼부부", "청년"],
    category: "apartment",
  },
    {
    id: 4,
    title: "가락동 원룸 전월세",
    address: "서울특별시 송파구 가락동",
    region: "서울",
    depositLabel: "보증금 500만",
    monthlyRentLabel: "월세 55만",
    latitude: 37.4964,
    longitude: 127.1207,
    tags: ["원룸", "역세권", "전월세"],
    category: "oneRoom",
  },
  {
    id: 5,
    title: "가락시장역 오피스텔",
    address: "서울특별시 송파구 가락동",
    region: "서울",
    depositLabel: "보증금 1,000만",
    monthlyRentLabel: "월세 70만",
    latitude: 37.4939,
    longitude: 127.1188,
    tags: ["오피스텔", "가락시장역"],
    category: "officetel",
  },
  {
    id: 6,
    title: "송파동 투룸 빌라",
    address: "서울특별시 송파구 송파동",
    region: "서울",
    depositLabel: "보증금 2,000만",
    monthlyRentLabel: "월세 85만",
    latitude: 37.5072,
    longitude: 127.1096,
    tags: ["투룸", "빌라", "송파"],
    category: "villa",
  },
  {
    id: 7,
    title: "문정동 청년 원룸",
    address: "서울특별시 송파구 문정동",
    region: "서울",
    depositLabel: "보증금 1,000만",
    monthlyRentLabel: "월세 60만",
    latitude: 37.4857,
    longitude: 127.1227,
    tags: ["청년", "원룸", "문정"],
    category: "oneRoom",
  },
  {
    id: 8,
    title: "석촌역 인근 오피스텔",
    address: "서울특별시 송파구 석촌동",
    region: "서울",
    depositLabel: "보증금 1,500만",
    monthlyRentLabel: "월세 75만",
    latitude: 37.5057,
    longitude: 127.1069,
    tags: ["오피스텔", "석촌역"],
    category: "officetel",
  },
  {
    id: 9,
    title: "방이동 원룸 월세",
    address: "서울특별시 송파구 방이동",
    region: "서울",
    depositLabel: "보증금 500만",
    monthlyRentLabel: "월세 58만",
    latitude: 37.5145,
    longitude: 127.1212,
    tags: ["원룸", "월세", "방이"],
    category: "oneRoom",
  },
  {
    id: 10,
    title: "오금동 투룸 전월세",
    address: "서울특별시 송파구 오금동",
    region: "서울",
    depositLabel: "보증금 3,000만",
    monthlyRentLabel: "월세 80만",
    latitude: 37.5029,
    longitude: 127.1285,
    tags: ["투룸", "전월세", "오금"],
    category: "villa",
  },
  {
    id: 11,
    title: "잠실동 소형 아파트",
    address: "서울특별시 송파구 잠실동",
    region: "서울",
    depositLabel: "보증금 5,000만",
    monthlyRentLabel: "월세 120만",
    latitude: 37.5133,
    longitude: 127.1002,
    tags: ["아파트", "잠실", "소형"],
    category: "apartment",
  },
  {
    id: 12,
    title: "삼전동 원룸",
    address: "서울특별시 송파구 삼전동",
    region: "서울",
    depositLabel: "보증금 1,000만",
    monthlyRentLabel: "월세 62만",
    latitude: 37.5021,
    longitude: 127.0928,
    tags: ["원룸", "삼전", "생활권"],
    category: "oneRoom",
  },
  {
    id: 13,
    title: "가락동 신축 오피스텔",
    address: "서울특별시 송파구 가락동",
    region: "서울",
    depositLabel: "보증금 2,000만",
    monthlyRentLabel: "월세 78만",
    latitude: 37.4991,
    longitude: 127.1219,
    tags: ["신축", "오피스텔", "가락"],
    category: "officetel",
  },
  {
    id: 14,
    title: "문정역 역세권 원룸",
    address: "서울특별시 송파구 문정동",
    region: "서울",
    depositLabel: "보증금 1,000만",
    monthlyRentLabel: "월세 65만",
    latitude: 37.4863,
    longitude: 127.1192,
    tags: ["역세권", "원룸", "문정역"],
    category: "oneRoom",
  },
  {
    id: 15,
    title: "장지역 인근 오피스텔",
    address: "서울특별시 송파구 장지동",
    region: "서울",
    depositLabel: "보증금 1,500만",
    monthlyRentLabel: "월세 68만",
    latitude: 37.4787,
    longitude: 127.1261,
    tags: ["오피스텔", "장지역"],
    category: "officetel",
  },
  {
    id: 16,
    title: "거여동 청년임대",
    address: "서울특별시 송파구 거여동",
    region: "서울",
    depositLabel: "보증금 300만",
    monthlyRentLabel: "월세 35만",
    latitude: 37.4935,
    longitude: 127.1433,
    tags: ["청년임대", "저렴한월세"],
    category: "villa",
  },
  {
    id: 17,
    title: "마천동 빌라 투룸",
    address: "서울특별시 송파구 마천동",
    region: "서울",
    depositLabel: "보증금 2,500만",
    monthlyRentLabel: "월세 72만",
    latitude: 37.4959,
    longitude: 127.1524,
    tags: ["빌라", "투룸", "마천"],
    category: "villa",
  },
  {
    id: 18,
    title: "가락동 반전세 원룸",
    address: "서울특별시 송파구 가락동",
    region: "서울",
    depositLabel: "보증금 3,000만",
    monthlyRentLabel: "월세 45만",
    latitude: 37.4975,
    longitude: 127.1168,
    tags: ["반전세", "원룸", "가락"],
    category: "oneRoom",
  },
  {
    id: 19,
    title: "송파역 근처 오피스텔",
    address: "서울특별시 송파구 송파동",
    region: "서울",
    depositLabel: "보증금 1,000만",
    monthlyRentLabel: "월세 73만",
    latitude: 37.4998,
    longitude: 127.1122,
    tags: ["오피스텔", "송파역"],
    category: "officetel",
  },
  {
    id: 20,
    title: "오금역 생활권 원룸",
    address: "서울특별시 송파구 오금동",
    region: "서울",
    depositLabel: "보증금 500만",
    monthlyRentLabel: "월세 52만",
    latitude: 37.5024,
    longitude: 127.1271,
    tags: ["원룸", "오금역", "생활권"],
    category: "oneRoom",
  },
  {
    id: 21,
    title: "잠실새내역 소형 원룸",
    address: "서울특별시 송파구 잠실동",
    region: "서울",
    depositLabel: "보증금 1,000만",
    monthlyRentLabel: "월세 80만",
    latitude: 37.5118,
    longitude: 127.0861,
    tags: ["원룸", "잠실새내", "역세권"],
    category: "oneRoom",
  },
  {
    id: 22,
    title: "방이동 신축 빌라",
    address: "서울특별시 송파구 방이동",
    region: "서울",
    depositLabel: "보증금 4,000만",
    monthlyRentLabel: "월세 90만",
    latitude: 37.5107,
    longitude: 127.1238,
    tags: ["신축", "빌라", "방이"],
    category: "villa",
  },
  {
    id: 23,
    title: "석촌호수 인근 오피스텔",
    address: "서울특별시 송파구 석촌동",
    region: "서울",
    depositLabel: "보증금 2,000만",
    monthlyRentLabel: "월세 88만",
    latitude: 37.5089,
    longitude: 127.1018,
    tags: ["오피스텔", "석촌호수"],
    category: "officetel",
  },
];